apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-service
  name: auth-service
  namespace: auth-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  type: LoadBalancer
  selector:
    app: auth-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
      app: auth-service
  name: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: 876708361421.dkr.ecr.ap-southeast-1.amazonaws.com/hris_user_service_app:v1
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          envFrom:
          - configMapRef:
              name: env-configmap  
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: DB_PASSWORD
            - name: SECRET_KEY_BASE
              value: c112d8b0ec0786d0f8ef1b5bb31daf43
          resources: {} # Define resource limits here
            # requests:
            #   memory: "256Mi"
            #   cpu: "500m"
            # limits:
            #   memory: "1Gi"
            #   cpu: "1"