apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
availabilityZones:
  - ap-southeast-1c
  - ap-southeast-1a
  - ap-southeast-1b
metadata:
  name: farget-hris-app-cluster-sg
  region: ap-southeast-1 # AWS Singapore region

# Node groups
nodeGroups:
  - name: ng-fargate
    instanceType: t3.small
    minSize: 1
    maxSize: 2 # Adjust as needed
    desiredCapacity: 2
    volumeSize: 20
    labels:
      app: hris_app
    # IAM
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      withAddonPolicies:
        autoScaler: true

# Fargate profiles
fargateProfiles:
  - name: auth-service-profile
    selectors:
      - namespace: auth-service

# CloudWatch
cloudWatch:
  clusterLogging:
    enableTypes:
      - api
      - audit
      - authenticator
      - controllerManager
    # Customize the log groups and retention settings as needed
    # For example:
    # - api
    #  enabled: true
    #  retentionInDays: 7
    # - audit
    #  enabled: true
    #  retentionInDays: 30
