apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

availabilityZones:
- ap-southeast-1a
- ap-southeast-1b
- ap-southeast-1c

metadata:
  name: hris-workshop
  region: ap-southeast-1
  version: '1.25'
  tags:
    karpenter.sh/discovery: hris-workshop
    created-by: eks-workshop-v2
    env: hris-workshop

iam:
  withOIDC: true

vpc:
  cidr: 10.42.0.0/16
  clusterEndpoints:
    privateAccess: true
    publicAccess: true

addons:
- name: vpc-cni
  version: v1.12.5-eksbuild.2
  configurationValues: "{\"env\":{\"ENABLE_PREFIX_DELEGATION\":\"true\", \"ENABLE_POD_ENI\":\"true\", \"POD_SECURITY_GROUP_ENFORCING_MODE\":\"standard\"}}"
  resolveConflicts: overwrite

managedNodeGroups:
- name: default
  desiredCapacity: 3
  minSize: 3
  maxSize: 6
  instanceType: m5.large
  privateNetworking: true
  releaseVersion: 1.25.6-20230304
  labels:
    workshop-default: 'yes'
