#
# A simple istio gateway for the hris app.
#

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: hris-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hris-app
spec:
  hosts:
  - "*"
  gateways:
  - hris-gateway
  http:
  - match:
    - uri:
        prefix: "/auth-service"
    rewrite:
      uri: "/"
    route:
    - destination:
        port:
          number: 80
        host: auth-service
  - match:
    - uri:
        prefix: "/ui"
    rewrite:
      uri: "/"
    route:
    - destination:
        port:
          number: 80
        host: ui
  - match:
    - uri:
        prefix: "/candidate-service"
    rewrite:
      uri: "/"
    route:
    - destination:
        port:
          number: 80
        host: candidate-service
  - match:
    - uri:
        prefix: "/employee-service"
    rewrite:
      uri: "/"
    route:
    - destination:
        port:
          number: 80
        host: employee-service
  - match:
    - uri:
        prefix: "/job-service"
    rewrite:
      uri: "/"
    route:
    - destination:
        port:
          number: 80
        host: job-service
