apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: hris-cluster-sg
  region: ap-southeast-1  
  version: "1.24"

vpc:
  subnets:
    public:
      pub-ap-southeast-1a:  
        id: "subnet-06f98ccbac518828d" 
      pub-ap-southeast-1b:  
        id: "subnet-002a8c13254fb0f59"  
      pub-ap-southeast-1c:
        id: "subnet-0ec65105ac5e0bd85"

managedNodeGroups:
  - name: hris-cluster-ng
    instanceType: t3.small
    minSize: 1
    maxSize: 3
    desiredCapacity: 2
    volumeSize: 20
    volumeType: gp3
    subnets:
      - pub-ap-southeast-1a  
      - pub-ap-southeast-1b 
      - pub-ap-southeast-1c 
    ssh:
      allow: true
      publicKeyName: aws-jenkins-key
    tags:
      Env: Dev
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      withAddonPolicies:
        autoScaler: true
