{
  "swagger": "2.0",
  "info": {
    "title": "API V1",
    "version": "v1"
  },
  "paths": {
    "/api/v1/signup": {
      "post": {
        "summary": "create registration",
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "user",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "user": {
                  "type": "object",
                  "properties": {
                    "email": {
                      "type": "string"
                    },
                    "password": {
                      "type": "string"
                    },
                    "username": {
                      "type": "string"
                    }
                  }
                }
              },
              "required": [
                "email",
                "password",
                "username"
              ]
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful"
          }
        }
      }
    },
    "/api/v1/login": {
      "post": {
        "summary": "create session upon login",
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "user",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "user": {
                  "type": "object",
                  "properties": {
                    "email": {
                      "type": "string"
                    },
                    "password": {
                      "type": "string"
                    }
                  }
                }
              },
              "required": [
                "email",
                "password"
              ]
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful"
          }
        }
      }
    },
    "/api/v1/logout": {
      "delete": {
        "summary": "delete session",
        "consumes": [
          "application/json"
        ],
        "security": [
          {
            "Bearer": {
            }
          }
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "type": "string",
            "description": "access_token"
          }
        ],
        "responses": {
          "200": {
            "description": "successful"
          }
        }
      }
    },
    "/api/v1/users": {
      "get": {
        "summary": "list users",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Bearer": {
            }
          }
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "type": "string",
            "description": "Access Token"
          }
        ],
        "responses": {
          "200": {
            "description": "get user list",
            "schema": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "users": {
                    "type": "array",
                    "items": {
                      "$ref": "#/components/schemas/user"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    }
  },
  "servers": [
    {
      "url": "http://{defaultHost}",
      "variables": {
        "defaultHost": {
          "default": "127.0.0.1:3001"
        }
      }
    }
  ],
  "components": {
    "schemas": {
      "error_response": {
        "type": "object",
        "properties": {
          "errors": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "description": "type of error"
                },
                "message": {
                  "type": "string",
                  "nullable": true
                }
              },
              "required": [
                "type",
                "message"
              ]
            }
          },
          "status": {
            "type": "integer"
          }
        },
        "required": [
          "errors",
          "status"
        ]
      },
      "user": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "username": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "roles": {
            "type": "array"
          }
        },
        "required": [
          "id",
          "username",
          "email",
          "password"
        ]
      }
    }
  },
  "securityDefinitions": {
    "Bearer": {
      "description": "...",
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }
}