{
  "swagger": "2.0",
  "info": {
    "title": "API V1",
    "version": "v1"
  },
  "paths": {
    "/api/v1/signup": {
      "post": {
        "summary": "Create Registration",
        "tags": [
          "Authentication"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "user",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "user": {
                  "type": "object",
                  "properties": {
                    "email": {
                      "type": "string",
                      "default": "employee@email.com"
                    },
                    "password": {
                      "type": "string",
                      "default": "abcABC1"
                    },
                    "username": {
                      "type": "string",
                      "default": "emp1"
                    }
                  },
                  "required": [
                    "email",
                    "password",
                    "username"
                  ]
                },
                "role": {
                  "type": "string",
                  "default": "employee"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful"
          },
          "422": {
            "description": "unprocessable entity - custom validation error"
          }
        }
      }
    },
    "/api/v1/login": {
      "post": {
        "summary": "Create Session upon Login",
        "tags": [
          "Authentication"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "user",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "user": {
                  "type": "object",
                  "properties": {
                    "email": {
                      "type": "string",
                      "default": "hrisadmin@example.com"
                    },
                    "password": {
                      "type": "string",
                      "default": "abcABC1"
                    }
                  },
                  "required": [
                    "email",
                    "password"
                  ]
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful"
          },
          "401": {
            "description": "unprocessable entity - missing email"
          }
        }
      }
    },
    "/api/v1/logout": {
      "delete": {
        "summary": "Delete Session",
        "tags": [
          "Authentication"
        ],
        "consumes": [
          "application/json"
        ],
        "security": [
          {
            "Bearer": {
            }
          }
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "type": "string",
            "description": "access_token"
          }
        ],
        "responses": {
          "200": {
            "description": "Logout successful"
          },
          "401": {
            "description": "Token invalid or expired"
          }
        }
      }
    },
    "/api/v1/users": {
      "get": {
        "summary": "list users",
        "tags": [
          "Users"
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Bearer": {
            }
          }
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "type": "string",
            "description": "Access Token"
          },
          {
            "name": "per_page",
            "in": "query",
            "type": "integer",
            "description": "no of items per page",
            "default": 3
          },
          {
            "name": "page",
            "in": "query",
            "type": "integer",
            "description": "page no",
            "default": 1
          }
        ],
        "responses": {
          "200": {
            "description": "get user list"
          }
        }
      }
    },
    "/api/v1/users/{id}": {
      "get": {
        "summary": "show user",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "Bearer": {
            }
          }
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "type": "string",
            "description": "Access Token"
          },
          {
            "name": "id",
            "in": "path",
            "type": "string",
            "description": "User ID",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful"
          }
        }
      }
    },
    "/api/v1/users/{id}/assign_role": {
      "post": {
        "summary": "Assign a role to a user",
        "tags": [
          "Users"
        ],
        "consumes": [
          "application/json"
        ],
        "security": [
          {
            "Bearer": {
            }
          }
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "type": "string",
            "description": "Access Token"
          },
          {
            "name": "id",
            "in": "path",
            "type": "string",
            "required": true
          },
          {
            "name": "role",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "role": {
                  "type": "string",
                  "default": "employee",
                  "enum": [
                    "user",
                    "administrator",
                    "hr_manager",
                    "employee",
                    "candidate"
                  ]
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "role assigned"
          },
          "401": {
            "description": "forbidden"
          }
        }
      }
    },
    "/api/v1/users/{id}/remove_role": {
      "delete": {
        "summary": "Delete a role to a user",
        "tags": [
          "Users"
        ],
        "consumes": [
          "application/json"
        ],
        "security": [
          {
            "Bearer": {
            }
          }
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "type": "string",
            "description": "Access Token"
          },
          {
            "name": "id",
            "in": "path",
            "type": "string",
            "required": true
          },
          {
            "name": "role",
            "in": "body",
            "type": "string",
            "description": "Role to assign",
            "default": "employee"
          }
        ],
        "responses": {
          "200": {
            "description": "Remove Role"
          },
          "401": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/api/v1/users/update_username": {
      "patch": {
        "summary": "Update a user's username",
        "tags": [
          "Users"
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Bearer": {
            }
          }
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "type": "string",
            "description": "Access Token"
          },
          {
            "name": "user",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "username": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Username updated"
          },
          "422": {
            "description": "Validation errors"
          }
        }
      }
    },
    "/api/v1/users/get_by_email": {
      "post": {
        "summary": "Get user by email",
        "tags": [
          "Users"
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Bearer": {
            }
          }
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "type": "string",
            "description": "Access Token"
          },
          {
            "name": "user",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "email": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User Found"
          },
          "404": {
            "description": "User not found by email"
          }
        }
      }
    }
  },
  "servers": [
    {
      "url": "http://{defaultHost}",
      "variables": {
        "defaultHost": {
          "default": "127.0.0.1:3000"
        }
      }
    }
  ],
  "components": {
    "schemas": {
      "error_response": {
        "type": "object",
        "properties": {
          "errors": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "description": "type of error"
                },
                "message": {
                  "type": "string",
                  "nullable": true
                }
              },
              "required": [
                "type",
                "message"
              ]
            }
          },
          "status": {
            "type": "integer"
          }
        },
        "required": [
          "errors",
          "status"
        ]
      },
      "user": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "username": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "roles": {
            "type": "array"
          }
        },
        "required": [
          "id",
          "username",
          "email",
          "password"
        ]
      }
    }
  },
  "securityDefinitions": {
    "Bearer": {
      "description": "...",
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }
}