apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth-service
resources:
- namespace.yaml
- secrets.yaml
- configMap.yaml
- serviceAccount.yaml
- service.yaml
- service-pgsql.yaml
- deployment.yaml
